name: Smart_Lab
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  firebase_storage: ^12.3.0
  file_picker: ^8.1.2
  uuid: ^4.5.0
  cloud_firestore: ^5.4.1
  url_launcher: ^6.3.0
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  image_gallery_saver: ^2.0.3
  screenshot: ^3.0.0
  qr_code_scanner: ^1.0.1
  firebase_auth: ^5.2.1
  universal_html: ^2.2.4
  permission_handler: ^11.3.1
  flutter_file_dialog: ^3.0.2

flutter_icons:
    android: true
    ios: true
    image_path: "lib/assets/aitsmartlabslogo.png"  # Path to your logo
    adaptive_icon_background: "#FFFFFF"  # Optional: You can specify a background color for Android adaptive icons
    adaptive_icon_foreground: "lib/assets/aitsmartlabslogo.png"  # Optional: Adaptive icon foreground


flutter:
  uses-material-design: true
  assets:
    - lib/assets/scan_qr_icon.png
    - lib/assets/history_icon.png
    - lib/assets/generate_qr_icon.png
    - lib/assets/wifi_icon.png
    - lib/assets/website_icon.png
    - lib/assets/pdf_icon.png
    - lib/assets/print_qr.png
    - lib/assets/home_edit_qr.jpg
    - lib/assets/home_generate_qr.jpg
    - lib/assets/aitlogoo.png
    - lib/assets/aitsmartlabslogo.png