// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwzbyp2aX_7BMoBGA4DQuJnBXWhaYvvIM',
    appId: '1:383564120676:web:4d31c67d6d052aa59ed571',
    messagingSenderId: '383564120676',
    projectId: 'smartlabsait',
    authDomain: 'smartlabsait.firebaseapp.com',
    storageBucket: 'smartlabsait.appspot.com',
    measurementId: 'G-ZBRVQTJNSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1G53hKgFphRRNFPYWrcKW4vY8OwfBMvg',
    appId: '1:383564120676:android:9097c612051d1ffa9ed571',
    messagingSenderId: '383564120676',
    projectId: 'smartlabsait',
    storageBucket: 'smartlabsait.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA26PR8ny77vsHzV25MzH2yA67YA7l6OH4',
    appId: '1:383564120676:ios:a6f72d853b98ade69ed571',
    messagingSenderId: '383564120676',
    projectId: 'smartlabsait',
    storageBucket: 'smartlabsait.appspot.com',
    iosBundleId: 'com.example.smartlabs',
  );
}
